version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: schedule_api_php
        volumes:
            - .:/var/www
        ports:
            - "9000:9000"
        networks:
            - schedule_api

    nginx:
        image: nginx:latest
        container_name: schedule_api_webserver
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - database
        networks:
            - schedule_api

    database:
        image: mariadb:latest
        container_name: schedule_api_database
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: schedule
            MYSQL_ROOT_PASSWORD: password
        networks:
            - schedule_api

networks:
    schedule_api:

volumes:
    db-data:
        driver: local
